# This is a config for E2B sandbox template.
# You can use template ID (2t9jkatfat1ppu2ncx0f) or template name (vibe-ai-app-nextjs-v3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-ai-app-nextjs-v3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-ai-app-nextjs-v3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-ai-app-nextjs-v3')

team_id = "24782f2a-1503-485d-95fb-9d27d74fb306"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-ai-app-nextjs-v3"
template_id = "2t9jkatfat1ppu2ncx0f"
